# Generated by Django 2.1.7 on 2019-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0002_profile_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.CharField(max_length=150),
        ),
    ]
