# Generated by Django 2.1.7 on 2019-07-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0003_auto_20190723_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderimage',
            name='founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lostfoundapp.Founder'),
        ),
        migrations.AddField(
            model_name='loserimage',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lostfoundapp.Loser'),
        ),
    ]
