# Generated by Django 2.1.7 on 2019-07-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0005_auto_20190723_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
    ]
