# Generated by Django 2.1.7 on 2019-07-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0006_auto_20190724_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.CharField(max_length=200),
        ),
    ]
