# Generated by Django 2.1.7 on 2019-07-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0007_auto_20190724_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loser',
            name='date_lost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
