# Generated by Django 2.1.7 on 2019-07-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0008_auto_20190725_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_confirm', models.BooleanField()),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostfoundapp.Founder')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostfoundapp.Loser')),
            ],
        ),
        migrations.RemoveField(
            model_name='foundrecord',
            name='founder',
        ),
        migrations.RemoveField(
            model_name='foundrecord',
            name='loser',
        ),
        migrations.DeleteModel(
            name='FoundRecord',
        ),
    ]
