# Generated by Django 2.1.7 on 2019-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0010_auto_20190727_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loser',
            name='date_lost',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
