# Generated by Django 2.1.7 on 2019-07-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0011_auto_20190728_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchedrecord',
            name='match_confirm',
        ),
    ]
