# Generated by Django 2.1.7 on 2019-07-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0014_auto_20190730_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='loser',
            old_name='profile',
            new_name='user',
        ),
    ]
