# Generated by Django 2.1.7 on 2019-07-31 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0016_auto_20190730_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedrecord',
            name='match_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchedrecord',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostfoundapp.FounderImage'),
        ),
        migrations.AlterField(
            model_name='matchedrecord',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostfoundapp.LoserImage'),
        ),
    ]
