# Generated by Django 2.1.7 on 2019-08-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0017_auto_20190731_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
