# Generated by Django 2.1.7 on 2019-08-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfoundapp', '0018_auto_20190811_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderimage',
            name='date_found',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='loserimage',
            name='date_lost',
            field=models.DateTimeField(null=True),
        ),
    ]
